# Generated by Django 3.2.4 on 2021-06-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_nome_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='nome_pessoa',
            new_name='pessoa',
        ),
    ]
