# Generated by Django 3.2.4 on 2021-06-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_rename_nome_pessoa_receita_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='pessoa',
            new_name='nome_pessoa',
        ),
    ]
